name: Cloud Python Automation CI Pipeline 

on:
 push:
   branches: ["main"]
 pull_request:
   branches: ["main"]
 workflow_dispatch: #allows manual trigger from GitHub UI
 schedule:
   #Runs automatically every hour at minute 0 (POSIX Cron Syntax)
   - cron: '0 * * * *'

jobs:
  run-pipeline:
    runs-on: ${{ matrix.os }}

    strategy: 
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python environment (${{ matrix.python-version }})
        uses: actions/setup-python@v5
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psutil pytest

      - name: Execute Master Automation Pipeline
        run: |
          python3 main_pipeline.py
        if: runner.os != 'Windows'
      
      #Windows Powershell syntax adjustment for executing Python
      - name: Executive Master Automation Pipeline (Windows)
        run: |
          python main_pipeline.py
        if: runner.os == 'Windows'

      - name: Upload Executive Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: system-health-report-${{ matrix.os }}-py${{ matrix.python-version }}
          path: system_health_report.md